name: deployment of next-js-app2

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest 
     
    steps:
    - uses: actions/checkout@v4
    - name: "build image"
      run: docker build -t vijkes/next-js-app .
    - name: "docker login"
      run: echo "${secrets.DOCKERPASS}" | docker login -u ${secrets.DOCKERUSER}
    # - name: "docker push"
    #   run: docker push vijkes/next-js-app:$(date +%Y%m%d)

